apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: ntnx-csi-psp
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedHostPaths:
  - pathPrefix: /var/lib/kubelet/plugins_registry/
  - pathPrefix: /var/lib/kubelet/plugins/csi.nutanix.com/
  - pathPrefix: /var/lib/kubelet
  - pathPrefix: /dev
  - pathPrefix: /etc/iscsi
  - pathPrefix: /sbin/iscsiadm
  - pathPrefix: /lib/modules
  - pathPrefix: /
  - pathPrefix: /lib64/ld-linux-x86-64.so.2
  volumes:
  - hostPath
  - secret
  - configMap
  - emptyDir
  hostNetwork: true
  hostPorts:
  - min: 9808
    max: 9808
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
